project:
  type: website

website:
  title: "Catalogo Videoclub"
  navbar:
    left:
      - href: videoclub_catalogue_link_results.qmd
        text: Home
      - href: explora_catalogo.qmd
        text: Explorador

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true